name: Build Arch Packages

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch, change as needed

jobs:
  build:
    runs-on: ubuntu-latest  # This uses the Ubuntu runner to start, but Arch will run inside Docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arch Linux Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest bash -c "
            pacman -Syu --noconfirm base-devel git &&
            # Loop through directories and build each PKGBUILD
            for dir in */; do
              if [ -f \"$dir/PKGBUILD\" ]; then
                echo \"Building package in $dir\"
                cd $dir
                makepkg -si --noconfirm --syncdeps --cleanbuild
                cd ..
              fi
            done
          "

      - name: Upload built packages
        uses: actions/upload-artifact@v3
        with:
          name: arch-packages
          path: '*.pkg.tar.zst'  # Adjust if necessary to match the built packages

